### ISSUE TITLE
 conv2d() received an invalid combination of arguments

### ISSUE THREAD

**Issue by flyingfish7777** [Zj-BinXia/ENLCA#10]
File "/root/ENLA/models/enlcn.py", line 65, in forward
    x = self.tail(res)
TypeError: conv2d() received an invalid combination of arguments - got (Tensor, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, !Parameter!, !Parameter!, !tuple!, !tuple!, !tuple!, int)

help~~~~~QAQ

**Comment by Zj-BinXia** [comment]
torch的版本是1.8吗？

**Comment by flyingfish7777** [comment]
> torch的版本是1.8吗？

不是，哦谢谢，提供了一个纠正思路，原来我要换成1.8﻿     ε≡٩(๑>₃<)۶
