### ISSUE TITLE
随着训练进行，PSNR反而越来越低

### ISSUE THREAD

**Issue by EchoXu98** [Zj-BinXia/ENLCA#11]
您好！请问当训练时，在DIV2K数据集下生成的bin文件夹里的数据有什么作用？是使用这个生成的数据进行训练吗？因为当我直接使用DIV2K数据集进行训练时，即使用DIV2K_train_HR和，DIV2K_train_LR_bicubic进行训练时，出现了随着训练epoch数的增加，PSNR反而降低的问题。

**Comment by Zj-BinXia** [comment]
bin文件夹是放二进制文件的。这个现象挺反常的，我没遇到过，你可以重新训练一下试试？
