### ISSUE TITLE
ENLCA的位置报错didn't match because some of the arguments have invalid types: (Tensor, Tensor, Tensor, tuple of (bool, bool), tuple of (int, int), tuple of (int, int), int)

### ISSUE THREAD

**Issue by DeepBlueNight** [Zj-BinXia/ENLCA#14]
TypeError: conv2d() received an invalid combination of arguments - got (Tensor, Tensor, Tensor, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, Tensor, tuple of (bool, bool), tuple of (int, int), tuple of (int, int), int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Tensor, Tensor, tuple of (bool, bool), tuple of (int, int), tuple of (int, int), int)

**Comment by Zj-BinXia** [comment]
Do you use pytorch==1.8? high version pytorch will cause the error.

**Comment by DeepBlueNight** [comment]
是。知道问题了谢作者
