### ISSUE TITLE
why？？？

### ISSUE THREAD

**Issue by Ashore-lz** [Zj-BinXia/ENLCA#2]
TypeError: conv2d() received an invalid combination of arguments - got (Tensor, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, tuple of ints padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)
 * (Tensor input, Tensor weight, Tensor bias, tuple of ints stride, str padding, tuple of ints dilation, int groups)
      didn't match because some of the arguments have invalid types: (Tensor, Parameter, Parameter, tuple, tuple, tuple, int)

**Comment by Zj-BinXia** [comment]
Do you revise the code?  I can run the code successfully. If you want to run EDSR, please use the https://github.com/sanghyun-son/EDSR-PyTorch.

**Comment by Ashore-lz** [comment]
> Do you revise the code? I can run the code successfully. If you want to run EDSR, please use the https://github.com/sanghyun-son/EDSR-PyTorch.

I only run ENLCA, all the configurations meet the configuration in EDSR, but I don't know why this error is reported when running, I only changed the code of the dataset location

**Comment by Zj-BinXia** [comment]
You should use torch==1.8. if torch>=1.10, the code will report the error.
