### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by xuanyili97** [Zj-BinXia/ENLCA#4]
File "/data2/cnu_lxy001/ENLCA-master/src/trainer.py", line 49, in train
    sr, comparative_loss = self.model(lr, 0)
ValueError: too many values to unpack (expected 2)
I also read this code :
https://github.com/sanghyun-son/EDSR-PyTorch/blob/master/src/trainer.py
loss = self.loss(sr, hr)
It is different ,why? and how to solve this problem?

**Comment by Zj-BinXia** [comment]
yes, except the L1 loss, we also introduce the contrastive loss.

**Comment by xuanyili97** [comment]
File "/data2/cnu_lxy001/ENLCA-master/src/trainer.py", line 49, in train
sr, comparative_loss = self.model(lr, 0)
ValueError: too many values to unpack (expected 2)
### This question has been solved.by the way of writting them separately.
sr = self.model(lr, 0)
comparative_loss = self.model(lr, 0)
