### ISSUE TITLE
why use rgb_mean and rgb_std in super-resolution task?

### ISSUE THREAD

**Issue by clearlon** [Zj-BinXia/ENLCA#6]
Hi,
Thank you for your great work. The rgb_mean and the rgb_std are usually used in high-level vision. Why do you use them in super-resolution task?

**Comment by Zj-BinXia** [comment]
For a fair comparison with the backbone EDSR, we adopt the same rgb_mean and the rgb_std operation as EDSR did. However, empirically, it is useless, and you can choose to delete it.

**Comment by clearlon** [comment]
I get it. Thanks for your knid reply.
